### ISSUE TITLE
Apa itu Dudududu Nananana

### ISSUE THREAD

**Issue by imandana** [bintangDiyantoro/idstackblog#1]
Tolong apa itu Nanana.... hehehe

> Tambahkan Ninu Ninu Ninu
`<p> Dari Imandana </p>`

@bintangDiyantoro 
 #

**Comment by bintangDiyantoro** [comment]
Wakakakakaka itu hanya isu yang tidak perlu dipercaya

**Comment by imandana** [comment]
Well done
